skip-check:
  - CKV_GCP_29
  - CKV_GCP_62
  - CKV_GCP_78
  - CKV_GCP_80
  - CKV_GCP_81
  - CKV_GCP_83
  - CKV2_GCP_13
  - CKV_GCP_54
  - CKV_GCP_111
  - CKV_GCP_109
  - CKV_GCP_60
  - CKV_GCP_53
  - CKV_GCP_110
  - CKV_GCP_6
  - CKV_GCP_108
  - CKV_GCP_52
  - CKV_GCP_51
